# Generated by Django 5.1.3 on 2024-11-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='LabTestCategoryId',
        ),
        migrations.RemoveField(
            model_name='labtestprescription',
            name='LabTestId',
        ),
        migrations.RemoveField(
            model_name='labtestprescription',
            name='AppointmentId',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='MedicineCategoryId',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='MedicineId',
        ),
        migrations.RemoveField(
            model_name='medicinestock',
            name='MedicineId',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='AppointmentId',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='LabTestCategory',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='LabTestPrescription',
        ),
        migrations.DeleteModel(
            name='MedicineCategory',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='MedicineStock',
        ),
        migrations.DeleteModel(
            name='MedicinePrescription',
        ),
    ]
